name: Test Components

on: [workflow_dispatch]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      python-version: 3.10.0
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -y pytest
        pip install -y requirements.txt
    - name: Unit test with pytest
      run: |
        python -m pytest tests/units
